# Generated by Django 2.0.2 on 2018-02-21 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.Enquete')),
            ],
        ),
    ]
